### PR TITLE
enhanced

### LINKED ISSUE #1: About MLFlow and how to integrate it as part of Data science workflow.
-  Hands on ML Flow Walkthrough.
-  Screenshot of the mlflow UI.
-  Use mlflow to track the parameters for your housing library code.

### PR DESCRIPTION
**Pull request by neo3249**

### CODE REVIEW

**Review by RoshanRoy97 — CHANGES_REQUESTED** [review]
Please attach the screenshot of the mlflow UI along with the command used to launch the MLFlow server.

**Comment by RoshanRoy97** [comment]
> Please attach the screenshot of the mlflow UI along with the command used to launch the MLFlow server.

Saw the screenshots, it'd have been better if they were attached to the PR instead of the issue.

**Review by RoshanRoy97 — APPROVED** [review]
Approved

**Comment by neo3249** [comment]
Screenshots of ML Flow UI : 

image_1
image-2
image-3
image-4
image-5

**Comment by neo3249** [comment]
> > Please attach the screenshot of the mlflow UI along with the command used to launch the MLFlow server.
> 
> Saw the screenshots, it'd have been better if they were attached to the PR instead of the issue.

Sure, have attached the same. Thanks!

**Pull request merged**
